#config/schedule.yml

metrics_job:
  cron: "30 1 * * *"
  class: "MetricsGenerationWorker"
  queue: metrics

followers_job:
  cron: "15 18 * * *"
  class: "MembersAsFollowersWorker"
  queue: default

