name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          RAILS_ENV: test
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev

      - name: Bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup & create Database
        run: |
          bundle exec rake decidim:generate_external_test_app
          bundle exec rails db:create db:schema:load
        env:
          RAILS_ENV: test
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres

      - name: Precompile assets
        run: bundle exec rake assets:precompile
        env:
          RAILS_ENV: test

      # - name: Setup Code Climate test-reporter
      #   run: |
      #     curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      #     chmod +x ./cc-test-reporter
      #     ./cc-test-reporter before-build

      - name: Run RSpec
        run: SIMPLECOV=1 CODECOV=1 bundle exec rake
        env:
          RAILS_ENV: test
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres

      # - name: Publish code coverage
      #   run: |
      #     export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
      #     ./cc-test-reporter after-build -r "$CC_TEST_REPORTER_ID"
      #   env:
      #     CC_TEST_REPORTER_ID: dc93f2c0d045a6fd7b2d2a9b03dfaf2c3b298c520605744bc0283a7535d5dc92